GET http://localhost:8080/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMiIsImlhdCI6MTc2MTkyMzE3MSwiZXhwIjoxNzYxOTI2NzcxfQ.EZIdKUJuzVLOiBfxw03ZWIUegQJ1dwGni6fr8rosErY

<> 2025-10-14T094850.200.json
<> 2025-10-14T094622.200.json
