POST http://60.205.57.52:8080/backend/api/search
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyIiwiaWF0IjoxNzYzNDI3NjAxLCJleHAiOjE3NjM0MzEyMDF9.CkWXbFtk5D_o9jp2UJ8k-ZazoVbkUQ-K-ILR1sbejeA

{
  "query": "AI",
  "filters": [
    {
      "sourceType": "DOCUMENT",
      "maxResults": 5,
      "safeSearch": true
    },
    {
      "sourceType": "VIDEO",
      "maxResults": 3,
      "safeSearch": true
    },
    {
      "sourceType": "IMAGE",
      "maxResults": 8,
      "safeSearch": true
    }
  ]
}
