PUT http://localhost:8080/api/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImlhdCI6MTc2MDQwNjI5MCwiZXhwIjoxNzYwNDA5ODkwfQ.2O7-7u0L_fV5ff5sKPwkmmgEDq9XdV3hCI7W5e8FJdQ
Content-Type: application/json

{
  "newUsername": "newUsername",
  "newEmail": "newemail@example.com"
}

<> 2025-10-14T094907.200.txt
<> 2025-10-14T094831.200.txt
<> 2025-10-14T094737.200.txt
